# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: "0.12"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@latest
  - npm install

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # We test multiple Windows shells because of prior stdout buffering issues
  # filed against Grunt. https://github.com/joyent/node/issues/3584
  - ps: "npm test # PowerShell" # Pass comment to PS for easier debugging
  - cmd: npm test

build: off

matrix:
  fast_finish: true

# Set build version format here instead of in the admin panel.
version: "{build}"

cache:
  - node_modules -> package.json
